Aula 8/Exercicio1/Controllers/CategoriaController.cs
using Exercicio1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercicio1.Controllers
{
    public class CategoriaController : Controller
    {
        private HotelariaBDEntities db = new HotelariaBDEntities();
        // GET: Categoria
        public ActionResult Index()
        {
            var categorias = db.Categoria.ToList();
            return View(categorias);
        }

        public ActionResult Inserir()
        {
            return View();
        }

        public ActionResult Alterar(int id)
        {
            Categoria categoria = db.Categoria.Find(id);
            return View(categoria);

        }

        public ActionResult Excluir(int id)
        {
            Categoria categoria = db.Categoria.Find(id);
            return View(categoria);
        }

        public ActionResult ErroExcluir()
        {
            return View();
        }
    }
}

Aula 8/Exercicio1/Controllers/CidadeController.cs
using Exercicio1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercicio1.Controllers
{
    public class CidadeController : Controller
    {
        private HotelariaBDEntities db = new HotelariaBDEntities();
        // GET: Cidade
        public ActionResult Index()
        {
            var cidades = db.Cidade.ToList();
            return View(cidades);
        }

        public ActionResult Inserir()
        {
            return View();
        }

        public ActionResult Alterar(int id)
        {
            Cidade cidade = db.Cidade.Find(id);
            return View(cidade);
        }

        public ActionResult Excluir(int id)
        {
            Cidade cidade = db.Cidade.Find(id);
            return View(cidade);
        }

        public ActionResult ErroExcluir()
        {
            return View();
        }

    }
}

Aula 8/Exercicio1/Controllers/QuartoController.cs
using Exercicio1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercicio1.Controllers
{
    public class QuartoController : Controller
    {
        private HotelariaBDEntities db = new HotelariaBDEntities();
        // GET: Quarto
        public ActionResult Index()
        {
            var quartos = db.Quarto.Include("TipoQuarto").Include("Estabelecimento").ToList();
            return View(quartos);
        }

        public ActionResult Inserir()
        {
            ViewBag.IdEstabelecimento = new SelectList(db.Estabelecimento, "IdEstabelecimento", "NomeComercial");
            ViewBag.IdTipoQuarto = new SelectList(db.TipoQuarto, "IdTipoQuarto", "Descricao");
            return View();
        }

        public ActionResult Alterar(int id)
        {
            Quarto quartos = db.Quarto.Find(id);
            ViewBag.IdEstabelecimento = new SelectList(db.Estabelecimento, "IdEstabelecimento", "NomeComercial", quartos.IdEstabelecimento);
            ViewBag.IdTipoQuarto = new SelectList(db.TipoQuarto, "IdTipoQuarto", "Descricao", quartos.IdTipoQuarto);
            return View(quartos);
        }

        public ActionResult Excluir(int id)
        {
            Quarto quartos = db.Quarto.Find(id);
            ViewBag.IdEstabelecimento = new SelectList(db.Estabelecimento, "IdEstabelecimento", "NomeComercial", quartos.IdEstabelecimento);
            ViewBag.IdTipoQuarto = new SelectList(db.TipoQuarto, "IdTipoQuarto", "Descricao", quartos.IdTipoQuarto);
            return View(quartos);
        }

        public ActionResult ErroExcluir()
        {
            return View();
        }
    }
}

Aula 8/Exercicio1/Views/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hospedagem Online- @ViewBag.Title</title>
    <link href="@Url.Content("~")" rel="stylesheet" />

</head>


<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hospedagem Online", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Estabelecimentos", "Index", "Estabelecimento")</li>
                    <li>@Html.ActionLink("Tipos de Quarto", "Index", "TipoQuarto")</li>
                    <li>@Html.ActionLink("Quartos", "Index", "Quarto")</li>
                    <li>@Html.ActionLink("Cidades", "Index", "Cidade")</li>
                    <li>@Html.ActionLink("Categorias", "Index", "Categoria")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <script src="@Url.Content("~/Scripts/jquery-3.5.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>